#ifndef OMS_ORDER_H
#define OMS_ORDER_H

#include <string>
#include <chrono>
#include <variant> // For std::variant, if used elsewhere, or can be removed if not.
#include <optional> // Added for std::optional

namespace oms {
namespace core {

enum class OrderType {
    MARKET,
    LIMIT,
    STOP_LIMIT,
    BRACKET_OCO, // Added
    ICEBERG,     // Added
    AMO          // Added
};

enum class OrderSide {
    BUY,
    SELL
};

enum class OrderStatus {
    NEW,
    PENDING_NEW,
    SUBMITTED,
    OPEN,
    PARTIALLY_FILLED,
    FILLED,
    PENDING_CANCEL,
    CANCELLED,
    REJECTED,
    EXPIRED
    // Align with FSM states from spec
};

struct Order {
    std::string clientOrderId;      // Global unique order ID generated by OMS
    std::string brokerOrderId;      // ID from the broker, populated after submission
    std::string symbol;             // e.g., "RELIANCE_NSE_EQ"
    OrderType type;                 // Removed default initializer
    OrderSide side;                 // Removed default initializer
    double quantity = 0.0;
    double filledQuantity = 0.0;
    double remainingQuantity = 0.0; // Added: quantity - filledQuantity
    std::optional<double> price;    // For LIMIT, STOP_LIMIT
    std::optional<double> stopPrice; // For STOP_LIMIT
    OrderStatus status;             // Removed default initializer
    std::chrono::system_clock::time_point creationTimestamp; // Changed from timestamp
    std::chrono::system_clock::time_point lastUpdateTimestamp; // Added
    // Add other fields: timeInForce, exchange, etc.

    // Method declarations (implementations are in Order.cpp)
    void updateQuantities(double quantityFilledInThisExecution);
    bool isTerminal() const;
};

} // namespace core
} // namespace oms
#endif // OMS_ORDER_H
